title: "solvaholic"
logo: /assets/img/my_avatar.jpeg
author: "@solvaholic"
author_url_keybase: "https://keybase.io/solvaholic"
author_url_twitter: "https://twitter.com/solvaholic"
repository: solvaholic/solvaholic.github.io
description:
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
timezone: America/New_York
jekyll_compose:
  default_front_matter:
    posts:
      tags: TODO
plugins:
  - jekyll-mentions
  - jekyll-github-metadata
  - jemoji
