#!/bin/sh

# bundle config set --local path 'vendor/gems'
# bundle config set --local without 'production'

set -e

cd "$(git rev-parse --show-toplevel)" || exit

# https://github.com/github/scripts-to-rule-them-all/tree/master/script

# Check/install prerequisites

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle install
fi
